---
- name: Install base packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker Engine & Compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes
  notify: Restart Docker

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Enable & start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Verify Docker works
  command: docker ps
  register: docker_ps
  changed_when: false

- name: Show docker ps output
  debug:
    var: docker_ps.stdout
